config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cats, except: :destroy
  root "cats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord

    CAT_COLORS = [
        "Black",
        "White",
        "Brown",
        "Ginger",
        "Mixed"
    ]

    GENDER = [
        "F",
        "M"
    ]

    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: {in: CAT_COLORS}
    validates :sex, inclusion: {in: GENDER}
    validate :birth_date_cannot_be_future

    def birth_date_cannot_be_future
        today = Date.today
        if birth_date > today
            errors.add(:birth_date,"Cannot be in the future")
        end
    end

    def age
        today = Date.today
        today.year - birth_date.year
    end

    has_many :rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord

    STATUS = [
        "APPROVED",
        "PENDING",
        "DENIED"
    ]

    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: {in: STATUS}
    validate :does_not_overlap_approved_request

    def overlapping_requests
        CatRentalRequest.where("cat_id = ?",:cat_id).where("? < end_date",:start_date)
    end

    def overlapping_approved_requests
        overlapping_approved_requests.where("status = 'APPROVED'")
    end

    def does_not_overlap_approved_request
        overlapping_approved_requests.exists?#(self)
    end

    belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        render :show
    end

    def create

    end

    def update

    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end

    private
    def cat_params
        params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<% path = action == :new ? cats_url : cat_url(cat) %>
<% submit = action == :new ? "Create" : "Update" %>

<form action="<%= path %>" method="POST">
    <% if action == :edit %>
        <input type="hidden" name="_method" value="PATCH">  
    <% end %>
    <input type="text" name="cats[name]" value="<%= cat.name %>">
    <br>
    <br>
    <label>Gender: </label>
    <label for="male">M</label>
    <input type="radio" name="cats[sex]" id="male" <%= cat.sex == "M" ? "checked" : "" %>>
    <label for="female">F</label>
    <input type="radio" name="cats[sex]" id="female" <%= cat.sex == "F" ? "checked" : "" %>>
    <br>
    <br>
    <select name="cats[color]" value="<%= cat.color %>">
        <option value="color" disabled <%= action == :new ? "selected" : "" %>>Color</option>
        <% Cat::CAT_COLORS.each do |color| %>
            <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %>><%= color %></option>
        <% end %>
    </select>
    <br>
    <br>
    <label for="birth_date">Birth Date: </label>
    <input type="date" name="cats[birth_date]" id="birth_date" value="<%= cat.birth_date %>">
    <br>
    <br>
    <textarea name="cats[description]"><%= cat.description %></textarea>
    <br>
    <br>
    <input type="submit" value=<%= submit %>>
</form>
<a href="<%= path %>">Back</a>

app/views/cats/edit.html.erb
<h1>Edit Cat</h1>
<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<table>
<th>
    <td>id</td>
    <td>name</td>
    <td>color</td>
    <td>sex</td>
    <td>birth_date</td>
    <td>description</td>
    <td>inspect</td>
</th>
<% @cats.each do |cat| %>
    <tr>
        <td><%= cat.id %></td>
        <td><%= cat.name %></td>
        <td><%= cat.color %></td>
        <td><%= cat.sex %></td>
        <td><%= cat.birth_date %></td>
        <td><%= cat.description %></td>
        <td><a href="<%= cat_url(cat.id) %>">Inspect</a></td>
    </tr>
<% end %>
</table>
<br>
<a href="<%= new_cat_url %>">New Cat</a>

app/views/cats/new.html.erb
<h1>Create Cat</h1>
<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1>Name: <%= @cat.name %></h1>
<ul>
    <li><%= @cat.color %></li>
    <li><%= @cat.birth_date %></li>
    <li><%= @cat.sex %></li>
    <li><%= @cat.description %></li>
</ul>
<a href="<%= edit_cat_url(@cat) %>">Edit Cat</a>
<br>
<br>
<a href="<%= cats_url %>">To All Cats</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>